name: Call Pipleine

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: DeployApp
        run: railway up
        env: 
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      
      - name: Slack notif
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with: 
          payload: |
            {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA 56 CI/CD Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name*: UWU"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email*: myemail@email.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation*: A0111111N"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository*:\n${{ github.repositoryUrl }}"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "railway link"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "GO TO LINK",
                    "emoji": true
                  }
                }
              }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
            